version: '3'
services:
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: admin_employees
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - 3306:3306
  
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - 3000:3000
    environment:
      DB_HOST: localhost
      DB_PORT: 3306
      DB_USERNAME: admin
      DB_PASSWORD: admin123
      DB_NAME: admin_employees
    depends_on:
      - mysql
